spring.application.name=jwt-package

jwt.excluded-paths= /v3/api-docs/**, /swagger-ui/**, /actuator/**, /public/**, /swagger/**, /webjars/**

# Define a validade do token para 12 horas, por exemplo
#jwt.expiration-time=43200000